### PR TITLE
unmarshal: fix panic from reading beyond slice

### LINKED ISSUE #440: Panic in unmarshalV3Header
The following example program causes `panic: runtime error: index out of range [6] with length 6` in `unmarshalV3Header`

```go
package main

import "github.com/gosnmp/gosnmp"

func main() {
	payload := []byte("0\x04\x02\x020\x03")
	g := &gosnmp.GoSNMP{}
	_, _ = g.SnmpDecodePacket(payload)
}
```

Go Playground link: https://go.dev/play/p/LUNaK4VmF-7

Panic message

```
panic: runtime error: index out of range [6] with length 6

goroutine 1 [running]:
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalV3Header(0x3003?, {0xc0000a4068?, 0xc0000a406a?, 0x4?}, 0x4?, 0x4e9476?)
	/tmp/gopath217892337/pkg/mod/github.com/gosnmp/gosnmp@v1.35.0/v3.go:339 +0xc5a
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalHeader(0xc00009ae28, {0xc0000a4068, 0x6, 0x6}, 0xc0000bc000)
	/tmp/gopath217892337/pkg/mod/github.com/gosnmp/gosnmp@v1.35.0/marshal.go:1009 +0x5f3
github.com/gosnmp/gosnmp.(*GoSNMP).SnmpDecodePacket(0xc00009ae28, {0xc0000a4068, 0x6, 0x6})
	/tmp/gopath217892337/pkg/mod/github.com/gosnmp/gosnmp@v1.35.0/gosnmp.go:539 +0xde
main.main()
	/tmp/sandbox1215514355/prog.go:10 +0x70
```

Relevant code:
https://github.com/gosnmp/gosnmp/blob/33df32e33fbd043727a4a117a0ef6f2183607113/v3.go#L336-L341

### PR DESCRIPTION
**Pull request by n3integration**
Resolves #440

Expand the bounds check of the `packet` bytes to prevent reading beyond the available number of bytes

### CODE REVIEW

**Comment by SuperQ** [comment]
Would you mind adding the example problem slice as a new unit test?

**Review by SuperQ — APPROVED** [review]
Nice, thanks!

**Comment by n3integration** [comment]
Hey @SuperQ + @TimRots 👋 - thanks for reviewing the PR! Is anything else pending that I need to look into or update before being approved+merged?

**Review by TimRots — APPROVED** [review]
Sorry for late approve, was sick last weeks.

**Comment by SuperQ** [comment]
No worries, hope you're feeling better.

**Pull request merged**
