### PR TITLE
Prevent panic by avoiding OOB read in parseLength

### PR DESCRIPTION
**Pull request by hdm**
This patch prevents a corrupted response from leading to a panic in the decoder. A better patch would involve redoing parseLength to return an error and updating all callers, but this would be extensive, and this change results in the right behavior (the packet fails to decode, instead of triggering a panic).

Signed-off-by: HD Moore <x@hdm.io>

### CODE REVIEW

**Comment by SuperQ** [comment]
It looks like the tests are failing due to Debian bullseye release. I'll take a look.

**Comment by SuperQ** [comment]
https://github.com/gosnmp/gosnmp/pull/355 will fix the build/test problems.

**Comment by hdm** [comment]
^ merged the main branch back, this should be ready to land

**Review by TimRots — APPROVED** [review]

**Comment by TimRots** [comment]
@SuperQ could you accept this PR as-is, if I add the error handling that @hdm suggested in a separate PR?

**Review by SuperQ — APPROVED** [review]
Yes, this is fine as a workaround.

LGTM

**Pull request merged**
