### PR TITLE
Add net-snmp validation testing

### PR DESCRIPTION
**Pull request by upsampled**
#448 

running `go test` with `-tags=netsnmp` will cause the test to use packets generated by net-snmp as expected values. This requires libsnmpd to be installed and cgo. Adding `-rec=true` to this will also record the expected packets as files under `/testdata`. These files can then be used without cgo in normally testing.

An additional pcap generating feature was also added, when `-pcap $DIR` is added to `go test` that directory will be filled with the expected and generated packets as pcaps. This allows for debugging using wireshark's parsers.

### CODE REVIEW

**Comment by upsampled** [comment]
Ok so the one thing that I cannot get around is the need to have global flag switches in the `gosnmp_test.go` file. In order to get extra options for `go test` you have to have the the `flag` types in the global context. Otherwise you will get a `flag provided but not defined: -rec` error:

```go
var (
	rec  = flag.Bool("rec", false, "record and use net-snmp expected outputs, else use recorded values [if true requires libsnmp/cgo]. ")
	pcap = flag.String("pcap", "", "dir to put exp and got data as pcap files, no pcaps made if blank.")
)
```

Aside from that, this is the basic validation framework mentioned in #448. I did adopt a record/playback mechanism similar to `crypto/tls` to allow test to run quickly and without cgo.

**Comment by upsampled** [comment]
Ok, this is basically the initial implementation. Squashed all commits. Still failing the lint check because of the previously mentioned testing flags. 

Ready for feedback.

**Comment by upsampled** [comment]
#453 was detected by testing and fixed

**Comment by upsampled** [comment]
Ok, so I few more issues/commits so that this PR will completely unblock slayercat/GoSNMPServer#21. Done making changes now, for real this time.

**Comment by SuperQ** [comment]
For the linter issues, I would be fine with this in the `.golangci.yml`:

```yaml
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - gochecknoglobals
```

**Comment by upsampled** [comment]
@SuperQ I had to add a `nolintlint` to the `*_test.go` exception as well because i started to get errors from `v3_credentials_test.go` after your recomended change. I also got a lint error in a function i did not modify, `marshalUint64`, but I just corrected the issue anyhow.

**Review by SuperQ — APPROVED** [review]
Minor nit. Otherwise LGTM.

**Comment by SuperQ** [comment]
Another random thought, would it make sense to put the net-snmp code in a separate package? Or does it access too many `gosnmp` internals?

**Comment by upsampled** [comment]
@SuperQ I like the idea of a separate package as validation should mainly be done 'on the wire' (IE: packets or sessions). Made that change (required one method to have a public counterpart). Also bumped net and sys versions.

**Review by SuperQ — APPROVED** [review]
Nice

**Review by TimRots — APPROVED** [review]

**Pull request merged**
